all: singleton easy_solution

singleton: singleton.cpp
	g++ -o singleton singleton.cpp

easy_solution: easy_solution.cpp
	g++ -o easy_solution easy_solution.cpp

clean:
	rm -f singleton easy_solution
