all: factory_method easy_solution

factory_method: factory_method.cpp
	g++ -o factory_method factory_method.cpp

easy_solution: easy_solution.cpp
	g++ -o easy_solution easy_solution.cpp

clean:
	rm -f factory_method easy_solution
