all: abstract_factary easy_solution

abstract_factary: abstract_factary.cpp
	g++ -o abstract_factary abstract_factary.cpp

easy_solution: easy_solution.cpp
	g++ -o easy_solution easy_solution.cpp

clean:
	rm -f abstract_factary easy_solution
