all: prototype easy_solution

prototype: prototype.cpp
	g++ -o prototype prototype.cpp

easy_solution: easy_solution.cpp
	g++ -o easy_solution easy_solution.cpp

clean:
	rm -f prototype easy_solution
